### ISSUE TITLE
multiple UI instances may run at same time

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/rvc-mac#3]

**Comment by nmtitov** [comment]
I tried to run executable twice and it didn't happen to me. Could you explain what's going on?

**Comment by jjr840430** [comment]
@nmtitov Yes, I tried to run the multiple instances from Xcode.

**Comment by ni4** [comment]
@jjr840430 I guess you mean @nmtitov :)
Actually it may happen for Mac applications during running from XCode - normal launch services should not allow this. Or debug/release versions have different app IDs.
Anyway, add some check for running instances in applicationWillFinishLaunching may be easily added.
